phpbr_app_main:
    resource: "@PhpbrAppBundle/Resources/config/routing/main.yml"

phpbr_app_fos:
    resource: "@PhpbrAppBundle/Resources/config/routing/fos.yml"

phpbr_app_artigo:
    resource: "@PhpbrAppBundle/Resources/config/routing/artigo.yml"
    prefix: /artigos/