parameters:
    my_user_provider.class: Phpbr\Bundle\AppBundle\Security\Core\User\FOSUBUserProvider
    gravatar.class: Phpbr\Bundle\AppBundle\Gravatar
    gravatar.twig_extension.class: Phpbr\Bundle\AppBundle\Twig\GravatarExtension

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        # arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id}]
        arguments: [@fos_user.user_manager,{facebook: facebook_id }]
    phpbr_app.registration.form.type:
        class: Phpbr\Bundle\AppBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: phpbr_user_registration }
    gravatar:
        class: "%gravatar.class%"

    gravatar.twig_extension:
        class: "%gravatar.twig_extension.class%"
        public: false
        tags:
            - { name: twig.extension }
