Phpbr\Bundle\AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 4
                max: 20
