Phpbr\Bundle\AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 4
                max: 20

Phpbr\Bundle\AppBundle\Entity\Artigo:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: titulo
    properties:
        titulo:
            - NotBlank: ~
            - Length:
                min: 4
                max: 155
        texto:
            - NotBlank: ~