language: php

php:
    - 5.4

before_install:
    - composer self-update
    - composer update

before_script:
    - composer install -n

script:
    - bin/phpunit -c app/

notifications:
    email:
        - phpbr@yahoo.ca

