language: php

php:
    - 5.4

env:
    - SYMFONY_VERSION=2.6.*

before_script:
    - composer self-update
    - composer install --no-interaction
    - chmod -R 777 app/cache app/logs
    - app/console cache:warmup --env=dev
    - chmod -R 777 app/cache app/logs
    - sleep 5

script:
    - bin/phpunit -c app/

notifications:
    email:
        - phpbr@yahoo.ca

