parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     phpbr
    database_user:     root
    database_password: root

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            pt_BR

    # A secret key that's used to generate certain security-related tokens
    secret:            TedEj8&*#fefDE?!!@d3445U9deFeECNEJFekfNDphp_-009-#!BR

    debug_toolbar:          true
    debug_redirects:        false
    use_assetic_controller: true
    knp_disqus.api_key:     test
    knp_disqus.secret_key:  test
    knp_disqus.lorem.shortname:     test