Phpbr\Bundle\AppBundle\Entity\Forum\Topico:
    type: entity
    table: forum_topico
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        assunto:
            type: string
            length: 255
        dataCriacao:
            type: datetime
    manyToOne:
        categoria:
            targetEntity: Phpbr\Bundle\AppBundle\Entity\Forum\Categoria
            inversedBy: categoria
            cascate: [persist]
            joinColumn:
                name: categoria_id
                referencedColumnName: id
                onDelete: CASCADE
        user:
            targetEntity: Phpbr\Bundle\AppBundle\Entity\User
            inversedBy: topico
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE
    oneToMany:
        mensagem:
            targetEntity: Phpbr\Bundle\AppBundle\Entity\Forum\Mensagem
            mappedBy: topico
            cascate: [persist, remove]
            orderBy:
                dataCriacao: ASC
    lifecycleCallbacks: {  }
