Phpbr\Bundle\AppBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: Phpbr\Bundle\AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        linkedin:
            type: string
            length: 255
        twitter:
            type: string
            length: 255
        github:
            type: string
            length: 255
        facebook_id:
            type: string
            length: 255
            nullable: true
        facebook_access_token:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
    oneToMany:
        artigos:
            targetEntity: Artigo
            mappedBy: user

