novo_artigo:
    path:     /novo
    defaults: { _controller: PhpbrAppBundle:Artigo:novo }

lista_artigos:
    path:   /
    defaults: { _controller: PhpbrAppBundle:Artigo:list }

ler_artigo:
    path: /ler/{slug}
    defaults: { _controller: PhpbrAppBundle:Artigo:ler }

