index:
    path:     /
    defaults: { _controller: "PhpbrAppBundle:Forum\Topico:index" }

ver:
    path:     /ver/{id}
    defaults: { _controller: "PhpbrAppBundle:Forum\Topico:ver" }

novo:
    path:     /novo
    defaults: { _controller: "PhpbrAppBundle:Forum\Topico:novo" }

deletar:
    path:     /deletar/{id}
    defaults: { _controller: "PhpbrAppBundle:Forum\Topico:deletar" }

nova_mensagem:
    path:     /{topico_id}/novaMensagem
    defaults: { _controller: "PhpbrAppBundle:Forum\Mensagem:novaMensagem" }

deletar_mensagem:
    path:     /deletar-mensagem/{id}
    defaults: { _controller: "PhpbrAppBundle:Forum\Mensagem:deletarMensagem" }
