forum_index:
    path:     /
    defaults: { _controller: "PhpbrAppBundle:Forum\Categoria:index" }

forum_ver_categoria:
    path:     /ver/{id}
    defaults: { _controller: "PhpbrAppBundle:Forum\Topico:ver" }

forum_ver_topico:
    path:     /ver-topico/{id}
    defaults: { _controller: "PhpbrAppBundle:Forum\Topico:verTopico" }

forum_ver_mensagem:
    path:     /ver-mensagem/{slug}
    defaults: { _controller: "PhpbrAppBundle:Forum\Mensagem:verMensagem" }

forum_novo_topico:
    path:     /novo
    defaults: { _controller: "PhpbrAppBundle:Forum\Topico:novo" }

forum_deletar:
    path:     /deletar/{id}
    defaults: { _controller: "PhpbrAppBundle:Forum\Topico:deletar" }

forum_nova_mensagem:
    path:     /{topico_id}/novaMensagem
    defaults: { _controller: "PhpbrAppBundle:Forum\Mensagem:novaMensagem" }

forum_deletar_mensagem:
    path:     /deletar-mensagem/{id}
    defaults: { _controller: "PhpbrAppBundle:Forum\Mensagem:deletarMensagem" }

