phpbr_app_inicial:
    path:     /
    defaults: { _controller: PhpbrAppBundle:Default:inicial }
phpbr_app_quemsomos:
    path:     /quem-somos
    defaults: { _controller: PhpbrAppBundle:Default:quemsomos }
phpbr_app_contato:
    path:     /contato
    defaults: { _controller: PhpbrAppBundle:Default:contato }
phpbr_app_colabore:
    path:     /colabore
    defaults: { _controller: PhpbrAppBundle:Default:colabore }
